import type { InstrumentPresetId, VoicingPolicy } from "./types";

export const voicingPolicies: Record<InstrumentPresetId, VoicingPolicy> = {
  piano_clear: {
    id: "piano_clear",
    name: "Piano Clear",
    bassRange: [36, 48],
    upperRange: [60, 76],
    upperVoiceCount: 3,
    preferRootBass: true,
    allowInversions: false,
    allowOmitFifth: false,
    allowExtensions: false,
    smoothVoiceLeading: true,
    maxUpperVoiceLeap: 7,
  },
  piano_smooth: {
    id: "piano_smooth",
    name: "Piano Smooth",
    bassRange: [36, 52],
    upperRange: [55, 74],
    upperVoiceCount: 4,
    preferRootBass: true,
    allowInversions: true,
    allowOmitFifth: true,
    allowExtensions: true,
    smoothVoiceLeading: true,
    maxUpperVoiceLeap: 5,
  },
  guitar_open: {
    id: "guitar_open",
    name: "Guitar Open Chords",
    bassRange: [40, 55],
    upperRange: [52, 76],
    upperVoiceCount: 4,
    preferRootBass: true,
    allowInversions: false,
    allowOmitFifth: false,
    allowExtensions: false,
    smoothVoiceLeading: false,
    maxUpperVoiceLeap: 12,
  },
  strings_quartet_basic: {
    id: "strings_quartet_basic",
    name: "String Quartet Basic",
    bassRange: [36, 52],
    upperRange: [48, 81],
    upperVoiceCount: 3,
    preferRootBass: true,
    allowInversions: true,
    allowOmitFifth: false,
    allowExtensions: true,
    smoothVoiceLeading: true,
    maxUpperVoiceLeap: 7,
  },
};
