import type { ProgressionTemplate } from "./types";

export const jazzBasic: ProgressionTemplate[] = [
  {
    id: "jazz-001",
    name: "ii7 - V7 - Imaj7",
    mode: "major",
    roman: ["ii7", "V7", "Imaj7"],
    functions: ["PD", "D", "T"],
    difficulty: 3,
    tags: ["jazz", "ii-V-I", "seventh"],
    description: "Quintessential jazz cadence.",
    cadence: "authentic",
  },
  {
    id: "jazz-002",
    name: "Imaj7 - vi7 - ii7 - V7",
    mode: "major",
    roman: ["Imaj7", "vi7", "ii7", "V7"],
    functions: ["T", "T", "PD", "D"],
    difficulty: 3,
    tags: ["jazz", "turnaround", "seventh"],
    description: "Jazz turnaround on a seventh-chord palette.",
    cadence: "loop",
  },
  {
    id: "jazz-003",
    name: "iii7 - vi7 - ii7 - V7",
    mode: "major",
    roman: ["iii7", "vi7", "ii7", "V7"],
    functions: ["T", "T", "PD", "D"],
    difficulty: 3,
    tags: ["jazz", "circle", "seventh"],
    description: "Diatonic circle-of-fifths through seventh chords.",
    cadence: "half",
  },
  {
    id: "jazz-004",
    name: "Imaj7 - VI7 - ii7 - V7",
    mode: "major",
    roman: ["Imaj7", "VI7", "ii7", "V7"],
    functions: ["T", "D", "PD", "D"],
    difficulty: 4,
    tags: ["jazz", "secondary-dominant", "seventh"],
    description: "Turnaround with secondary dominant V/ii (VI7).",
    cadence: "loop",
  },
  {
    id: "jazz-005",
    name: "ii7 - V7 - iii7 - vi7",
    mode: "major",
    roman: ["ii7", "V7", "iii7", "vi7"],
    functions: ["PD", "D", "T", "T"],
    difficulty: 3,
    tags: ["jazz", "deceptive", "seventh"],
    description: "Deceptive jazz cadence ending on vi7.",
    cadence: "deceptive",
  },
  {
    id: "jazz-006",
    name: "Imaj7 - IVmaj7 - viiø7 - III7 - vi7 - ii7 - V7 - Imaj7",
    mode: "major",
    roman: ["Imaj7", "IVmaj7", "viiø7", "III7", "vi7", "ii7", "V7", "Imaj7"],
    functions: ["T", "PD", "D", "D", "T", "PD", "D", "T"],
    difficulty: 5,
    tags: ["jazz", "extended", "secondary-dominant"],
    description: "Extended jazz cadence with secondary dominants.",
    cadence: "authentic",
  },
  {
    id: "jazz-007",
    name: "Imaj7 - ii7 - iii7 - IVmaj7",
    mode: "major",
    roman: ["Imaj7", "ii7", "iii7", "IVmaj7"],
    functions: ["T", "PD", "T", "PD"],
    difficulty: 3,
    tags: ["jazz", "ascending", "seventh"],
    description: "Stepwise ascending diatonic seventh chords.",
    cadence: "none",
  },
  {
    id: "jazz-008",
    name: "vi7 - ii7 - V7 - Imaj7",
    mode: "major",
    roman: ["vi7", "ii7", "V7", "Imaj7"],
    functions: ["T", "PD", "D", "T"],
    difficulty: 3,
    tags: ["jazz", "circle", "seventh"],
    description: "Four-bar jazz circle ending on tonic seventh.",
    cadence: "authentic",
  },
  {
    id: "jazz-009",
    name: "ii7 - V7 - Imaj7 - VI7",
    mode: "major",
    roman: ["ii7", "V7", "Imaj7", "VI7"],
    functions: ["PD", "D", "T", "D"],
    difficulty: 4,
    tags: ["jazz", "turnaround", "secondary-dominant"],
    description: "ii-V-I followed by V/ii to loop back.",
    cadence: "loop",
  },
  {
    id: "jazz-010",
    name: "Imaj7 - vi7 - ii7 - V7 - Imaj7",
    mode: "major",
    roman: ["Imaj7", "vi7", "ii7", "V7", "Imaj7"],
    functions: ["T", "T", "PD", "D", "T"],
    difficulty: 3,
    tags: ["jazz", "turnaround"],
    description: "Resolved turnaround back to Imaj7.",
    cadence: "authentic",
  },
  {
    id: "jazz-011",
    name: "iii7 - VI7 - ii7 - V7 - Imaj7",
    mode: "major",
    roman: ["iii7", "VI7", "ii7", "V7", "Imaj7"],
    functions: ["T", "D", "PD", "D", "T"],
    difficulty: 4,
    tags: ["jazz", "secondary-dominant"],
    description: "Backdoor approach via secondary dominants.",
    cadence: "authentic",
  },
  {
    id: "jazz-012",
    name: "Imaj7 - IVmaj7 - ii7 - V7",
    mode: "major",
    roman: ["Imaj7", "IVmaj7", "ii7", "V7"],
    functions: ["T", "PD", "PD", "D"],
    difficulty: 3,
    tags: ["jazz", "seventh"],
    description: "Common jazz intro using two major sevenths.",
    cadence: "half",
  },
];
