import { ProgressionTemplate } from "./types";

export const jazzBasic: ProgressionTemplate[] = [
  {
    id: "jazz_ii7_V7_Imaj7",
    title: "ii7 - V7 - Imaj7",
    mode: "major",
    difficulty: 3,
    roman: ["ii7", "V7", "Imaj7"],
    functions: ["PD", "D", "T"],
    tags: ["jazz", "ii-V-I", "essential"],
    description: "The fundamental jazz cadence. Every jazz musician must know this.",
  },
  {
    id: "jazz_Imaj7_vi7_ii7_V7",
    title: "Imaj7 - vi7 - ii7 - V7",
    mode: "major",
    difficulty: 4,
    roman: ["Imaj7", "vi7", "ii7", "V7"],
    functions: ["T", "T", "PD", "D"],
    tags: ["jazz", "turnaround", "standard"],
    description: "Common jazz turnaround. Rhythm changes A section.",
  },
  {
    id: "jazz_iii7_vi7_ii7_V7",
    title: "iii7 - vi7 - ii7 - V7",
    mode: "major",
    difficulty: 4,
    roman: ["iii7", "vi7", "ii7", "V7"],
    functions: ["T", "T", "PD", "D"],
    tags: ["jazz", "turnaround", "cycle"],
    description: "Circle of fifths turnaround, extended.",
  },
  {
    id: "jazz_Imaj7_VI7_ii7_V7",
    title: "Imaj7 - VI7 - ii7 - V7",
    mode: "major",
    difficulty: 5,
    roman: ["Imaj7", "VI7", "ii7", "V7"],
    functions: ["T", "D", "PD", "D"],
    tags: ["jazz", "secondary-dominant", "advanced"],
    description: "Secondary dominant VI7/ii leads to ii7, then V7 to I.",
  },
  {
    id: "jazz_ii7_V7_iii7_vi7",
    title: "ii7 - V7 - iii7 - vi7",
    mode: "major",
    difficulty: 4,
    roman: ["ii7", "V7", "iii7", "vi7"],
    functions: ["PD", "D", "T", "T"],
    tags: ["jazz", "deceptive", "turnaround"],
    description: "Deceptive resolution to iii7 instead of I, then cycle continues.",
  },
  {
    id: "jazz_full_turnaround",
    title: "Imaj7 - IVmaj7 - viiø7 - III7 - vi7 - ii7 - V7 - Imaj7",
    mode: "major",
    difficulty: 5,
    roman: ["Imaj7", "IVmaj7", "viiø7", "III7", "vi7", "ii7", "V7", "Imaj7"],
    functions: ["T", "PD", "D", "D", "T", "PD", "D", "T"],
    tags: ["jazz", "advanced", "full-cycle"],
    description: "Full circle progression with secondary dominants and half-diminished vii.",
  },
  {
    id: "jazz_ii7_V7_I6",
    title: "ii7 - V7 - I6",
    mode: "major",
    difficulty: 3,
    roman: ["ii7", "V7", "I"],
    functions: ["PD", "D", "T"],
    tags: ["jazz", "ii-V-I", "variant"],
    description: "ii-V-I resolving to I6 for a lighter sound.",
  },
  {
    id: "jazz_Imaj7_II7_ii7_V7",
    title: "Imaj7 - II7 - ii7 - V7",
    mode: "major",
    difficulty: 5,
    roman: ["Imaj7", "II7", "ii7", "V7"],
    functions: ["T", "D", "PD", "D"],
    tags: ["jazz", "secondary-dominant"],
    description: "Secondary dominant II7/V leading to ii7 then V7.",
  },
  {
    id: "jazz_minor_ii7b5_V7_i",
    title: "iiø7 - V7 - i",
    mode: "minor",
    difficulty: 3,
    roman: ["ii°", "V7", "i"],
    functions: ["PD", "D", "T"],
    tags: ["jazz", "minor", "ii-V-i"],
    description: "Minor ii-V-i with half-diminished ii chord. Essential minor jazz cadence.",
  },
  {
    id: "jazz_minor_ii7b5_V7b9_i",
    title: "iiø7 - V7b9 - i",
    mode: "minor",
    difficulty: 4,
    roman: ["ii°", "V7", "i"],
    functions: ["PD", "D", "T"],
    tags: ["jazz", "minor", "altered"],
    description: "Minor ii-V-i with altered dominant for extra tension.",
  },
  {
    id: "jazz_minor_turnaround",
    title: "i7 - iv7 - iiø7 - V7 - i7",
    mode: "minor",
    difficulty: 5,
    roman: ["i", "iv", "ii°", "V7", "i"],
    functions: ["T", "PD", "PD", "D", "T"],
    tags: ["jazz", "minor", "extended"],
    description: "Extended minor turnaround with predominant chain.",
  },
  {
    id: "jazz_Imaj7_vi7_ii7_V7_iiim7",
    title: "Imaj7 - vi7 - ii7 - V7 - iii7",
    mode: "major",
    difficulty: 5,
    roman: ["Imaj7", "vi7", "ii7", "V7", "iii7"],
    functions: ["T", "T", "PD", "D", "T"],
    tags: ["jazz", "extended", "deceptive"],
    description: "Extended turnaround with deceptive resolution to iii.",
  },
];
