import type { ProgressionTemplate } from "./types";

export const majorBasic: ProgressionTemplate[] = [
  {
    id: "maj-basic-001",
    name: "I - V - I (Authentic Cadence)",
    mode: "major",
    roman: ["I", "V", "I"],
    functions: ["T", "D", "T"],
    difficulty: 1,
    tags: ["basic", "cadence"],
    description: "Simplest authentic cadence demonstrating tonic-dominant-tonic motion.",
    cadence: "authentic",
  },
  {
    id: "maj-basic-002",
    name: "I - IV - V - I",
    mode: "major",
    roman: ["I", "IV", "V", "I"],
    functions: ["T", "PD", "D", "T"],
    difficulty: 1,
    tags: ["basic", "cadence", "classical"],
    description: "Textbook T-PD-D-T cycle.",
    cadence: "authentic",
  },
  {
    id: "maj-basic-003",
    name: "I - ii - V - I",
    mode: "major",
    roman: ["I", "ii", "V", "I"],
    functions: ["T", "PD", "D", "T"],
    difficulty: 1,
    tags: ["basic", "cadence"],
    description: "ii instead of IV as predominant.",
    cadence: "authentic",
  },
  {
    id: "maj-basic-004",
    name: "I - vi - IV - V (Doo-Wop / 50s)",
    mode: "major",
    roman: ["I", "vi", "IV", "V"],
    functions: ["T", "T", "PD", "D"],
    difficulty: 1,
    tags: ["basic", "pop", "doo-wop"],
    description: "Classic 1950s progression, often looped.",
    cadence: "loop",
  },
  {
    id: "maj-basic-005",
    name: "I - vi - ii - V",
    mode: "major",
    roman: ["I", "vi", "ii", "V"],
    functions: ["T", "T", "PD", "D"],
    difficulty: 2,
    tags: ["basic", "circle"],
    description: "Smooth descending fifth motion through the diatonic chords.",
    cadence: "loop",
  },
  {
    id: "maj-basic-006",
    name: "I - IV - I - V",
    mode: "major",
    roman: ["I", "IV", "I", "V"],
    functions: ["T", "PD", "T", "D"],
    difficulty: 1,
    tags: ["basic", "blues-flavor"],
    description: "Alternation between tonic, subdominant and dominant.",
    cadence: "half",
  },
  {
    id: "maj-basic-007",
    name: "I - V - vi - IV (Axis of Awesome)",
    mode: "major",
    roman: ["I", "V", "vi", "IV"],
    functions: ["T", "D", "T", "PD"],
    difficulty: 1,
    tags: ["basic", "pop"],
    description: "Ubiquitous modern pop loop.",
    cadence: "loop",
  },
  {
    id: "maj-basic-008",
    name: "I - iii - IV - V",
    mode: "major",
    roman: ["I", "iii", "IV", "V"],
    functions: ["T", "T", "PD", "D"],
    difficulty: 2,
    tags: ["basic", "ascending"],
    description: "Stepwise ascent in the bass.",
    cadence: "half",
  },
  {
    id: "maj-basic-009",
    name: "vi - IV - I - V",
    mode: "major",
    roman: ["vi", "IV", "I", "V"],
    functions: ["T", "PD", "T", "D"],
    difficulty: 1,
    tags: ["basic", "pop", "loop"],
    description: "Same chords as I-V-vi-IV reordered to start on vi.",
    cadence: "loop",
  },
  {
    id: "maj-basic-010",
    name: "I - V - IV - I",
    mode: "major",
    roman: ["I", "V", "IV", "I"],
    functions: ["T", "D", "PD", "T"],
    difficulty: 2,
    tags: ["basic", "plagal"],
    description: "Plagal closure after a dominant.",
    cadence: "plagal",
  },
  {
    id: "maj-basic-011",
    name: "I - ii - IV - V",
    mode: "major",
    roman: ["I", "ii", "IV", "V"],
    functions: ["T", "PD", "PD", "D"],
    difficulty: 2,
    tags: ["basic"],
    description: "Two-step predominant approach to the dominant.",
    cadence: "half",
  },
  {
    id: "maj-basic-012",
    name: "I - IV - vi - V",
    mode: "major",
    roman: ["I", "IV", "vi", "V"],
    functions: ["T", "PD", "T", "D"],
    difficulty: 2,
    tags: ["basic", "pop"],
    description: "Substitute tonic vi between IV and V.",
    cadence: "half",
  },
  {
    id: "maj-basic-013",
    name: "I - vi - iii - IV",
    mode: "major",
    roman: ["I", "vi", "iii", "IV"],
    functions: ["T", "T", "T", "PD"],
    difficulty: 3,
    tags: ["basic", "tonic-prolongation"],
    description: "Long tonic prolongation through tonic-substitute chords.",
    cadence: "none",
  },
  {
    id: "maj-basic-014",
    name: "I - iii - vi - IV",
    mode: "major",
    roman: ["I", "iii", "vi", "IV"],
    functions: ["T", "T", "T", "PD"],
    difficulty: 3,
    tags: ["basic", "tonic-prolongation"],
    description: "Descending thirds in tonic group landing on subdominant.",
    cadence: "none",
  },
  {
    id: "maj-basic-015",
    name: "I - IV - ii - V - I",
    mode: "major",
    roman: ["I", "IV", "ii", "V", "I"],
    functions: ["T", "PD", "PD", "D", "T"],
    difficulty: 2,
    tags: ["basic", "cadence"],
    description: "Two predominants in succession before resolution.",
    cadence: "authentic",
  },
  {
    id: "maj-basic-016",
    name: "I - vi - IV - ii - V - I",
    mode: "major",
    roman: ["I", "vi", "IV", "ii", "V", "I"],
    functions: ["T", "T", "PD", "PD", "D", "T"],
    difficulty: 3,
    tags: ["basic", "extended", "cadence"],
    description: "Six-bar extended cadence.",
    cadence: "authentic",
  },
  {
    id: "maj-basic-017",
    name: "I - V - vi - IV - V",
    mode: "major",
    roman: ["I", "V", "vi", "IV", "V"],
    functions: ["T", "D", "T", "PD", "D"],
    difficulty: 2,
    tags: ["basic", "pop"],
    description: "I-V-vi-IV with an added dominant turnaround.",
    cadence: "half",
  },
  {
    id: "maj-basic-018",
    name: "I - IV - I - V - I",
    mode: "major",
    roman: ["I", "IV", "I", "V", "I"],
    functions: ["T", "PD", "T", "D", "T"],
    difficulty: 1,
    tags: ["basic", "cadence"],
    description: "Plagal-then-authentic full cadence pattern.",
    cadence: "authentic",
  },
  {
    id: "maj-basic-019",
    name: "IV - I - V - vi",
    mode: "major",
    roman: ["IV", "I", "V", "vi"],
    functions: ["PD", "T", "D", "T"],
    difficulty: 2,
    tags: ["basic", "pop"],
    description: "Starts on the subdominant for a different feel.",
    cadence: "deceptive",
  },
  {
    id: "maj-basic-020",
    name: "vi - V - IV - V",
    mode: "major",
    roman: ["vi", "V", "IV", "V"],
    functions: ["T", "D", "PD", "D"],
    difficulty: 3,
    tags: ["basic"],
    description: "Hovering around the dominant with a brief subdominant lift.",
    cadence: "half",
  },
  {
    id: "maj-basic-021",
    name: "I - iii - vi - ii - V - I",
    mode: "major",
    roman: ["I", "iii", "vi", "ii", "V", "I"],
    functions: ["T", "T", "T", "PD", "D", "T"],
    difficulty: 3,
    tags: ["basic", "circle"],
    description: "Diatonic circle-of-fifths motion through the key.",
    cadence: "authentic",
  },
  {
    id: "maj-basic-022",
    name: "I - V - vi - iii - IV - I - IV - V",
    mode: "major",
    roman: ["I", "V", "vi", "iii", "IV", "I", "IV", "V"],
    functions: ["T", "D", "T", "T", "PD", "T", "PD", "D"],
    difficulty: 3,
    tags: ["basic", "canon", "pachelbel"],
    description: "Pachelbel canon in major.",
    cadence: "half",
  },
  {
    id: "maj-basic-023",
    name: "I - IV - V - vi - IV - V - I",
    mode: "major",
    roman: ["I", "IV", "V", "vi", "IV", "V", "I"],
    functions: ["T", "PD", "D", "T", "PD", "D", "T"],
    difficulty: 3,
    tags: ["basic", "extended"],
    description: "Two cadential gestures with a deceptive moment.",
    cadence: "authentic",
  },
  {
    id: "maj-basic-024",
    name: "I - vi - ii - V - I",
    mode: "major",
    roman: ["I", "vi", "ii", "V", "I"],
    functions: ["T", "T", "PD", "D", "T"],
    difficulty: 2,
    tags: ["basic", "circle"],
    description: "Smooth circle-of-fifths feel in five chords.",
    cadence: "authentic",
  },
  {
    id: "maj-basic-025",
    name: "I - IV - vi - iii - IV - I - ii - V",
    mode: "major",
    roman: ["I", "IV", "vi", "iii", "IV", "I", "ii", "V"],
    functions: ["T", "PD", "T", "T", "PD", "T", "PD", "D"],
    difficulty: 4,
    tags: ["basic", "extended"],
    description: "Long phrase with two predominant approaches.",
    cadence: "half",
  },
];
