import { ProgressionTemplate } from "./types";

export const majorBasic: ProgressionTemplate[] = [
  {
    id: "major_I_V_I",
    title: "I - V - I",
    mode: "major",
    difficulty: 1,
    roman: ["I", "V", "I"],
    functions: ["T", "D", "T"],
    tags: ["basic", "cadence", "authentic"],
    description: "The most fundamental authentic cadence. Tonic to dominant and back.",
  },
  {
    id: "major_I_IV_V_I",
    title: "I - IV - V - I",
    mode: "major",
    difficulty: 1,
    roman: ["I", "IV", "V", "I"],
    functions: ["T", "PD", "D", "T"],
    tags: ["basic", "cadence", "authentic"],
    description: "Complete authentic cadence with predominant preparation.",
  },
  {
    id: "major_I_ii_V_I",
    title: "I - ii - V - I",
    mode: "major",
    difficulty: 2,
    roman: ["I", "ii", "V", "I"],
    functions: ["T", "PD", "D", "T"],
    tags: ["basic", "cadence", "jazz-influenced"],
    description: "Classic ii-V-I progression, foundation of jazz harmony.",
  },
  {
    id: "major_I_vi_IV_V",
    title: "I - vi - IV - V",
    mode: "major",
    difficulty: 2,
    roman: ["I", "vi", "IV", "V"],
    functions: ["T", "T", "PD", "D"],
    tags: ["pop", "doo-wop", "classic"],
    description: "The classic 50s/doo-wop progression. T-T-PD-D loop.",
  },
  {
    id: "major_I_vi_ii_V",
    title: "I - vi - ii - V",
    mode: "major",
    difficulty: 3,
    roman: ["I", "vi", "ii", "V"],
    functions: ["T", "T", "PD", "D"],
    tags: ["jazz", "turnaround", "classic"],
    description: "Common turnaround progression in jazz standards.",
  },
  {
    id: "major_I_IV_I_V",
    title: "I - IV - I - V",
    mode: "major",
    difficulty: 1,
    roman: ["I", "IV", "I", "V"],
    functions: ["T", "PD", "T", "D"],
    tags: ["basic", "plagal", "blues"],
    description: "Alternating tonic-to-predominant and tonic-to-dominant.",
  },
  {
    id: "major_I_V_vi_IV",
    title: "I - V - vi - IV",
    mode: "major",
    difficulty: 2,
    roman: ["I", "V", "vi", "IV"],
    functions: ["T", "D", "T", "PD"],
    tags: ["pop", "axis", "modern"],
    description: "The ubiquitous Axis progression found in countless pop songs.",
  },
  {
    id: "major_I_iii_IV_V",
    title: "I - iii - IV - V",
    mode: "major",
    difficulty: 2,
    roman: ["I", "iii", "IV", "V"],
    functions: ["T", "T", "PD", "D"],
    tags: ["basic", "ascending"],
    description: "Ascending bass line creates a rising feeling.",
  },
  {
    id: "major_vi_IV_I_V",
    title: "vi - IV - I - V",
    mode: "major",
    difficulty: 3,
    roman: ["vi", "IV", "I", "V"],
    functions: ["T", "PD", "T", "D"],
    tags: ["pop", "alternative"],
    description: "Starting on the relative minor before moving to predominant.",
  },
  {
    id: "major_I_V_IV_I",
    title: "I - V - IV - I",
    mode: "major",
    difficulty: 1,
    roman: ["I", "V", "IV", "I"],
    functions: ["T", "D", "PD", "T"],
    tags: ["basic", "plagal"],
    description: "Dominant to subdominant, then back to tonic via plagal motion.",
  },
  {
    id: "major_I_ii_IV_V",
    title: "I - ii - IV - V",
    mode: "major",
    difficulty: 2,
    roman: ["I", "ii", "IV", "V"],
    functions: ["T", "PD", "PD", "D"],
    tags: ["basic", "predominant-chain"],
    description: "Two predominant chords in sequence before the dominant.",
  },
  {
    id: "major_I_IV_vi_V",
    title: "I - IV - vi - V",
    mode: "major",
    difficulty: 2,
    roman: ["I", "IV", "vi", "V"],
    functions: ["T", "PD", "T", "D"],
    tags: ["basic", "deceptive-motion"],
    description: "Predominant moving to tonic substitute then dominant.",
  },
  {
    id: "major_I_vi_iii_IV",
    title: "I - vi - iii - IV",
    mode: "major",
    difficulty: 3,
    roman: ["I", "vi", "iii", "IV"],
    functions: ["T", "T", "T", "PD"],
    tags: ["basic", "tonic-expansion"],
    description: "Extended tonic area with descending bass line.",
  },
  {
    id: "major_I_iii_vi_IV",
    title: "I - iii - vi - IV",
    mode: "major",
    difficulty: 3,
    roman: ["I", "iii", "vi", "IV"],
    functions: ["T", "T", "T", "PD"],
    tags: ["basic", "descending"],
    description: "Descending thirds progression: I, iii, vi, IV.",
  },
  {
    id: "major_I_IV_ii_V_I",
    title: "I - IV - ii - V - I",
    mode: "major",
    difficulty: 3,
    roman: ["I", "IV", "ii", "V", "I"],
    functions: ["T", "PD", "PD", "D", "T"],
    tags: ["basic", "extended"],
    description: "Extended cadence with two predominant approaches.",
  },
  {
    id: "major_I_vi_IV_ii_V_I",
    title: "I - vi - IV - ii - V - I",
    mode: "major",
    difficulty: 4,
    roman: ["I", "vi", "IV", "ii", "V", "I"],
    functions: ["T", "T", "PD", "PD", "D", "T"],
    tags: ["basic", "extended", "jazz"],
    description: "Full circle progression with tonic, predominant chain, dominant, tonic.",
  },
  {
    id: "major_I_V_vi_iii_IV_I_IV_V",
    title: "I - V - vi - iii - IV - I - IV - V",
    mode: "major",
    difficulty: 5,
    roman: ["I", "V", "vi", "iii", "IV", "I", "IV", "V"],
    functions: ["T", "D", "T", "T", "PD", "T", "PD", "D"],
    tags: ["pop", "long", "canon"],
    description: "Pachelbel-inspired 8-chord progression.",
  },
  {
    id: "major_I_IV_V_IV",
    title: "I - IV - V - IV",
    mode: "major",
    difficulty: 2,
    roman: ["I", "IV", "V", "IV"],
    functions: ["T", "PD", "D", "PD"],
    tags: ["pop", "loop"],
    description: "Looping progression alternating dominant and subdominant.",
  },
  {
    id: "major_I_V7_I",
    title: "I - V7 - I",
    mode: "major",
    difficulty: 1,
    roman: ["I", "V7", "I"],
    functions: ["T", "D", "T"],
    tags: ["basic", "cadence", "seventh"],
    description: "Authentic cadence with dominant seventh for stronger resolution.",
  },
  {
    id: "major_I_IV_V_vi",
    title: "I - IV - V - vi",
    mode: "major",
    difficulty: 2,
    roman: ["I", "IV", "V", "vi"],
    functions: ["T", "PD", "D", "T"],
    tags: ["basic", "deceptive", "cadence"],
    description: "Deceptive cadence: V resolves to vi instead of I.",
  },
  {
    id: "major_IV_V_I_vi",
    title: "IV - V - I - vi",
    mode: "major",
    difficulty: 3,
    roman: ["IV", "V", "I", "vi"],
    functions: ["PD", "D", "T", "T"],
    tags: ["pop", "anacrusis"],
    description: "Starting on predominant, resolving to tonic then deceptive motion.",
  },
  {
    id: "major_I_vi_IV_V7_I",
    title: "I - vi - IV - V7 - I",
    mode: "major",
    difficulty: 3,
    roman: ["I", "vi", "IV", "V7", "I"],
    functions: ["T", "T", "PD", "D", "T"],
    tags: ["basic", "extended", "classic"],
    description: "Classic extended cadence with V7 for rich resolution.",
  },
  {
    id: "major_ii_V_I_vi",
    title: "ii - V - I - vi",
    mode: "major",
    difficulty: 3,
    roman: ["ii", "V", "I", "vi"],
    functions: ["PD", "D", "T", "T"],
    tags: ["jazz", "turnaround"],
    description: "Turnaround with deceptive motion to relative minor.",
  },
  {
    id: "major_I_ii_iii_IV_V",
    title: "I - ii - iii - IV - V",
    mode: "major",
    difficulty: 4,
    roman: ["I", "ii", "iii", "IV", "V"],
    functions: ["T", "PD", "T", "PD", "D"],
    tags: ["basic", "ascending", "stepwise"],
    description: "Step-wise ascending chord progression.",
  },
  {
    id: "major_I_V7_vi_IV",
    title: "I - V7 - vi - IV",
    mode: "major",
    difficulty: 3,
    roman: ["I", "V7", "vi", "IV"],
    functions: ["T", "D", "T", "PD"],
    tags: ["pop", "axis-variant"],
    description: "Axis progression variant with dominant seventh.",
  },
  {
    id: "major_I_V7_vi_V",
    title: "I - V7 - vi - V",
    mode: "major",
    difficulty: 2,
    roman: ["I", "V7", "vi", "V"],
    functions: ["T", "D", "T", "D"],
    tags: ["pop", "loop"],
    description: "Alternating between tonic substitute and dominant.",
  },
  {
    id: "major_I_IV_V_I_V",
    title: "I - IV - V - I - V",
    mode: "major",
    difficulty: 2,
    roman: ["I", "IV", "V", "I", "V"],
    functions: ["T", "PD", "D", "T", "D"],
    tags: ["basic", "cadence", "extended"],
    description: "Authentic cadence extended with additional dominant.",
  },
  {
    id: "major_vi_IV_V_I",
    title: "vi - IV - V - I",
    mode: "major",
    difficulty: 2,
    roman: ["vi", "IV", "V", "I"],
    functions: ["T", "PD", "D", "T"],
    tags: ["pop", "loop"],
    description: "Starting on relative minor, resolving to tonic through dominant.",
  },
  {
    id: "major_ii7_V7_Imaj7",
    title: "ii7 - V7 - Imaj7",
    mode: "major",
    difficulty: 3,
    roman: ["ii7", "V7", "Imaj7"],
    functions: ["PD", "D", "T"],
    tags: ["basic", "jazz-influenced", "cadence"],
    description: "Essential ii-V-I jazz cadence with seventh chords.",
  },
  {
    id: "major_IV_V_iii_vi",
    title: "IV - V - iii - vi (Royal Road)",
    mode: "major",
    difficulty: 3,
    roman: ["IV", "V", "iii", "vi"],
    functions: ["PD", "D", "T", "T"],
    tags: ["pop", "japanese", "royal-road"],
    description: "王道進行 — iconic Japanese pop progression found in countless anime and J-pop songs.",
  },
  {
    id: "major_I_iii_IV_ii_V_I",
    title: "I - iii - IV - ii - V - I",
    mode: "major",
    difficulty: 3,
    roman: ["I", "iii", "IV", "ii", "V", "I"],
    functions: ["T", "T", "PD", "PD", "D", "T"],
    tags: ["basic", "stepwise", "extended"],
    description: "Stepwise chain from tonic through subdominants to dominant and tonic.",
  },
  {
    id: "major_I_vi_IV_ii_V",
    title: "I - vi - IV - ii - V",
    mode: "major",
    difficulty: 3,
    roman: ["I", "vi", "IV", "ii", "V"],
    functions: ["T", "T", "PD", "PD", "D"],
    tags: ["basic", "predominant-chain"],
    description: "Tonic substitution then double predominant chain to dominant.",
  },
  {
    id: "major_IV_V_I_iii_vi",
    title: "IV - V - I - iii - vi",
    mode: "major",
    difficulty: 3,
    roman: ["IV", "V", "I", "iii", "vi"],
    functions: ["PD", "D", "T", "T", "T"],
    tags: ["basic", "extended"],
    description: "Authentic cadence followed by descending tonic expansion.",
  },
  {
    id: "major_iii_vi_ii_V_I",
    title: "iii - vi - ii - V - I",
    mode: "major",
    difficulty: 4,
    roman: ["iii", "vi", "ii", "V", "I"],
    functions: ["T", "T", "PD", "D", "T"],
    tags: ["jazz", "circle", "fifths"],
    description: "Circle of fifths progression: iii-vi-ii-V-I.",
  },
  {
    id: "major_vi_V_IV_III",
    title: "vi - V - IV - III",
    mode: "major",
    difficulty: 4,
    roman: ["vi", "V", "IV", "III"],
    functions: ["T", "D", "PD", "T"],
    tags: ["pop", "descending", "epic"],
    description: "Descending bass line progression, popular in anime and cinematic music.",
  },
  {
    id: "major_I_vi_ii_IV_V7_I",
    title: "I - vi - ii - IV - V7 - I",
    mode: "major",
    difficulty: 4,
    roman: ["I", "vi", "ii", "IV", "V7", "I"],
    functions: ["T", "T", "PD", "PD", "D", "T"],
    tags: ["basic", "extended"],
    description: "Extended cadence with tonic substitute and two predominant chords.",
  },
  {
    id: "major_I_V7_vi_IV_V_I",
    title: "I - V7 - vi - IV - V - I",
    mode: "major",
    difficulty: 4,
    roman: ["I", "V7", "vi", "IV", "V", "I"],
    functions: ["T", "D", "T", "PD", "D", "T"],
    tags: ["basic", "extended", "classic"],
    description: "Axis progression variant extended to full authentic cadence.",
  },
  {
    id: "major_I_V_vi_iii_IV_I_ii_V",
    title: "I - V - vi - iii - IV - I - ii - V (Canon 15634125)",
    mode: "major",
    difficulty: 5,
    roman: ["I", "V", "vi", "iii", "IV", "I", "ii", "V"],
    functions: ["T", "D", "T", "T", "PD", "T", "PD", "D"],
    tags: ["pop", "canon", "long", "classic"],
    description: "Classic Pachelbel Canon progression ending with ii-V for a smoother loop.",
  },
  {
    id: "major_IV_V_iii_vi_ii_V_I",
    title: "IV - V - iii - vi - ii - V - I (Extended Royal Road)",
    mode: "major",
    difficulty: 5,
    roman: ["IV", "V", "iii", "vi", "ii", "V", "I"],
    functions: ["PD", "D", "T", "T", "PD", "D", "T"],
    tags: ["pop", "japanese", "royal-road", "long"],
    description: "Extended 王道進行 — Royal Road extended to full ii-V-I resolution.",
  },
  {
    id: "major_I_IV_vi_iii_ii_V_I",
    title: "I - IV - vi - iii - ii - V - I",
    mode: "major",
    difficulty: 5,
    roman: ["I", "IV", "vi", "iii", "ii", "V", "I"],
    functions: ["T", "PD", "T", "T", "PD", "D", "T"],
    tags: ["basic", "descending", "long"],
    description: "Descending chain through tonic expansion and predominant to final cadence.",
  },
  {
    id: "major_I_ii_V",
    title: "I - ii - V",
    mode: "major",
    difficulty: 1,
    roman: ["I", "ii", "V"],
    functions: ["T", "PD", "D"],
    tags: ["basic", "cadence"],
    description: "Tonic to predominant to dominant, the core of Western harmony.",
  },
  {
    id: "major_I_vi_V",
    title: "I - vi - V",
    mode: "major",
    difficulty: 1,
    roman: ["I", "vi", "V"],
    functions: ["T", "T", "D"],
    tags: ["basic", "simple"],
    description: "Tonic to relative minor to dominant.",
  },
  {
    id: "major_I_IV_I",
    title: "I - IV - I",
    mode: "major",
    difficulty: 1,
    roman: ["I", "IV", "I"],
    functions: ["T", "PD", "T"],
    tags: ["basic", "plagal"],
    description: "Plagal motion: tonic to subdominant and back, the Amen cadence.",
  },
  {
    id: "major_IV_I_V",
    title: "IV - I - V",
    mode: "major",
    difficulty: 1,
    roman: ["IV", "I", "V"],
    functions: ["PD", "T", "D"],
    tags: ["basic", "simple"],
    description: "Begins on subdominant, returns to tonic then to dominant.",
  },
  {
    id: "major_I_iii_IV",
    title: "I - iii - IV",
    mode: "major",
    difficulty: 1,
    roman: ["I", "iii", "IV"],
    functions: ["T", "T", "PD"],
    tags: ["basic", "ascending"],
    description: "Tonic to mediant to subdominant, gentle ascending sound.",
  },
  {
    id: "major_ii_V",
    title: "ii - V",
    mode: "major",
    difficulty: 1,
    roman: ["ii", "V"],
    functions: ["PD", "D"],
    tags: ["basic", "cadence", "jazz-prep"],
    description: "The bare predominant-to-dominant half-cadence, fundamental ii-V pair.",
  },
];
