import { ProgressionTemplate } from "./types";

export const minorBasic: ProgressionTemplate[] = [
  {
    id: "minor_i_V_i",
    title: "i - V - i",
    mode: "minor",
    difficulty: 1,
    roman: ["i", "V", "i"],
    functions: ["T", "D", "T"],
    tags: ["basic", "cadence", "harmonic-minor"],
    description: "Minor authentic cadence using harmonic minor raised leading tone.",
  },
  {
    id: "minor_i_iv_V_i",
    title: "i - iv - V - i",
    mode: "minor",
    difficulty: 2,
    roman: ["i", "iv", "V", "i"],
    functions: ["T", "PD", "D", "T"],
    tags: ["basic", "cadence", "harmonic-minor"],
    description: "Complete minor cadence with iv predominant.",
  },
  {
    id: "minor_i_iio_V_i",
    title: "i - ii° - V - i",
    mode: "minor",
    difficulty: 3,
    roman: ["i", "ii°", "V", "i"],
    functions: ["T", "PD", "D", "T"],
    tags: ["basic", "diminished", "cadence"],
    description: "Minor cadence with diminished ii chord as predominant.",
  },
  {
    id: "minor_i_VI_VII_i",
    title: "i - VI - VII - i",
    mode: "minor",
    difficulty: 2,
    roman: ["i", "VI", "VII", "i"],
    functions: ["T", "T", "D", "T"],
    tags: ["basic", "natural-minor", "aeolian"],
    description: "Natural minor progression, no raised leading tone.",
  },
  {
    id: "minor_i_VII_VI_V",
    title: "i - VII - VI - V",
    mode: "minor",
    difficulty: 3,
    roman: ["i", "VII", "VI", "V"],
    functions: ["T", "D", "T", "D"],
    tags: ["basic", "descending", "andalucian"],
    description: "Descending progression similar to Andalusian cadence.",
  },
  {
    id: "minor_i_iv_VII_III",
    title: "i - iv - VII - III",
    mode: "minor",
    difficulty: 3,
    roman: ["i", "iv", "VII", "III"],
    functions: ["T", "PD", "D", "T"],
    tags: ["basic", "natural-minor"],
    description: "Natural minor progression through subdominant and flat-VII.",
  },
  {
    id: "minor_i_VI_III_VII",
    title: "i - VI - III - VII",
    mode: "minor",
    difficulty: 2,
    roman: ["i", "VI", "III", "VII"],
    functions: ["T", "T", "T", "D"],
    tags: ["basic", "natural-minor"],
    description: "Mediant-chain in minor, all natural minor chords.",
  },
  {
    id: "minor_i_iv_i_V",
    title: "i - iv - i - V",
    mode: "minor",
    difficulty: 2,
    roman: ["i", "iv", "i", "V"],
    functions: ["T", "PD", "T", "D"],
    tags: ["basic", "plagal", "harmonic-minor"],
    description: "Plagal motion within tonic, then dominant preparation.",
  },
  {
    id: "minor_i_VII_III_VI",
    title: "i - VII - III - VI",
    mode: "minor",
    difficulty: 2,
    roman: ["i", "VII", "III", "VI"],
    functions: ["T", "D", "T", "T"],
    tags: ["basic", "circle", "fifths"],
    description: "Circle of fifths motion in natural minor.",
  },
  {
    id: "minor_i_iv_V7_i",
    title: "i - iv - V7 - i",
    mode: "minor",
    difficulty: 2,
    roman: ["i", "iv", "V7", "i"],
    functions: ["T", "PD", "D", "T"],
    tags: ["basic", "cadence", "seventh"],
    description: "Minor cadence with V7 for stronger resolution.",
  },
  {
    id: "minor_i_iv_iio_V7_i",
    title: "i - iv - ii° - V7 - i",
    mode: "minor",
    difficulty: 4,
    roman: ["i", "iv", "ii°", "V7", "i"],
    functions: ["T", "PD", "PD", "D", "T"],
    tags: ["basic", "extended", "cadence"],
    description: "Extended minor cadence with two predominant chords.",
  },
  {
    id: "minor_i_VI_iv_V7",
    title: "i - VI - iv - V7",
    mode: "minor",
    difficulty: 3,
    roman: ["i", "VI", "iv", "V7"],
    functions: ["T", "T", "PD", "D"],
    tags: ["basic", "deceptive"],
    description: "Tonic to major VI, then predominant chain to dominant.",
  },
  {
    id: "minor_i_bVII_bVI_V7",
    title: "i - bVII - bVI - V7",
    mode: "minor",
    difficulty: 3,
    roman: ["i", "VII", "VI", "V7"],
    functions: ["T", "D", "T", "D"],
    tags: ["basic", "descending", "rock"],
    description: "Descending bass with flat VII and flat VI, classic rock minor.",
  },
  {
    id: "minor_i_VII_III_VI_iio_V_i",
    title: "i - VII - III - VI - ii° - V - i",
    mode: "minor",
    difficulty: 5,
    roman: ["i", "VII", "III", "VI", "ii°", "V", "i"],
    functions: ["T", "D", "T", "T", "PD", "D", "T"],
    tags: ["basic", "extended", "baroque"],
    description: "Circle of fifths progression in minor, extended to seven chords.",
  },
  {
    id: "minor_i_V_VI_iv",
    title: "i - V - VI - iv",
    mode: "minor",
    difficulty: 3,
    roman: ["i", "V", "VI", "iv"],
    functions: ["T", "D", "T", "PD"],
    tags: ["basic", "mixed"],
    description: "Harmonic minor V leading to natural minor VI and iv.",
  },
  {
    id: "minor_vi_IV_I_V",
    title: "vi - IV - I - V",
    mode: "minor",
    difficulty: 3,
    roman: ["i", "iv", "V", "VI"],
    functions: ["T", "PD", "D", "T"],
    tags: ["basic", "deceptive-resolution"],
    description: "V resolves deceptively to VI instead of i.",
  },
  {
    id: "minor_i_III_iv_V",
    title: "i - III - iv - V",
    mode: "minor",
    difficulty: 3,
    roman: ["i", "III", "iv", "V"],
    functions: ["T", "T", "PD", "D"],
    tags: ["basic", "mediant"],
    description: "Mediant III leading to predominant iv and dominant V.",
  },
  {
    id: "minor_i_VII_iv_V",
    title: "i - VII - iv - V",
    mode: "minor",
    difficulty: 3,
    roman: ["i", "VII", "iv", "V"],
    functions: ["T", "D", "PD", "D"],
    tags: ["basic", "mixed"],
    description: "Mixing natural minor VII with harmonic minor V.",
  },
  {
    id: "minor_i_iv_i_V7_i",
    title: "i - iv - i - V7 - i",
    mode: "minor",
    difficulty: 2,
    roman: ["i", "iv", "i", "V7", "i"],
    functions: ["T", "PD", "T", "D", "T"],
    tags: ["basic", "plagal", "harmonic-minor"],
    description: "Plagal motion alternating with dominant seventh cadence.",
  },
  {
    id: "minor_i_VI_III_VII_i",
    title: "i - VI - III - VII - i",
    mode: "minor",
    difficulty: 3,
    roman: ["i", "VI", "III", "VII", "i"],
    functions: ["T", "T", "T", "D", "T"],
    tags: ["basic", "natural-minor", "loop"],
    description: "Natural minor loop through all diatonic chords, popular in Latin music.",
  },
  {
    id: "minor_i_VII_VI_V7_i",
    title: "i - VII - VI - V7 - i",
    mode: "minor",
    difficulty: 3,
    roman: ["i", "VII", "VI", "V7", "i"],
    functions: ["T", "D", "T", "D", "T"],
    tags: ["basic", "descending", "andalusian"],
    description: "Andalusian cadence variant with V7 for stronger resolution.",
  },
  {
    id: "minor_i_III_iv_VII_i",
    title: "i - III - iv - VII - i",
    mode: "minor",
    difficulty: 3,
    roman: ["i", "III", "iv", "VII", "i"],
    functions: ["T", "T", "PD", "D", "T"],
    tags: ["basic", "natural-minor", "cadence"],
    description: "Natural minor median chain resolving through subdominant to VII-i.",
  },
  {
    id: "minor_i_VI_iv_V_i",
    title: "i - VI - iv - V - i",
    mode: "minor",
    difficulty: 3,
    roman: ["i", "VI", "iv", "V", "i"],
    functions: ["T", "T", "PD", "D", "T"],
    tags: ["basic", "harmonic-minor", "cadence"],
    description: "Common minor progression with predominant and authentic cadence.",
  },
  {
    id: "minor_i_III_VII_VI_iv_V_i",
    title: "i - III - VII - VI - iv - V - i",
    mode: "minor",
    difficulty: 4,
    roman: ["i", "III", "VII", "VI", "iv", "V", "i"],
    functions: ["T", "T", "D", "T", "PD", "D", "T"],
    tags: ["basic", "extended", "natural-minor"],
    description: "Extended natural minor progression with full cadential resolution.",
  },
  {
    id: "minor_i_VI_III_iv_V_i",
    title: "i - VI - III - iv - V - i",
    mode: "minor",
    difficulty: 4,
    roman: ["i", "VI", "III", "iv", "V", "i"],
    functions: ["T", "T", "T", "PD", "D", "T"],
    tags: ["basic", "extended", "circle"],
    description: "Circle of fifths fragment in minor with authentic cadence.",
  },
  {
    id: "minor_i_iv_VII_VI_V7_i",
    title: "i - iv - VII - VI - V7 - i",
    mode: "minor",
    difficulty: 4,
    roman: ["i", "iv", "VII", "VI", "V7", "i"],
    functions: ["T", "PD", "D", "T", "D", "T"],
    tags: ["basic", "descending", "extended"],
    description: "Descending bass progression from subdominant through dominant preparation.",
  },
  {
    id: "minor_VI_VII_i_iv_V_i",
    title: "VI - VII - i - iv - V - i",
    mode: "minor",
    difficulty: 4,
    roman: ["VI", "VII", "i", "iv", "V", "i"],
    functions: ["T", "D", "T", "PD", "D", "T"],
    tags: ["basic", "extended"],
    description: "Starting on major VI, moving through VII to tonic then cadence.",
  },
  {
    id: "minor_i_V_VI_III_iv_V7_i",
    title: "i - V - VI - III - iv - V7 - i",
    mode: "minor",
    difficulty: 5,
    roman: ["i", "V", "VI", "III", "iv", "V7", "i"],
    functions: ["T", "D", "T", "T", "PD", "D", "T"],
    tags: ["basic", "extended", "long"],
    description: "Extended mixed minor progression blending harmonic and natural minor.",
  },
  {
    id: "minor_i_V_VII_VI_iio_V7_i",
    title: "i - V - VII - VI - ii° - V7 - i",
    mode: "minor",
    difficulty: 5,
    roman: ["i", "V", "VII", "VI", "ii°", "V7", "i"],
    functions: ["T", "D", "D", "T", "PD", "D", "T"],
    tags: ["basic", "descending", "extended", "long"],
    description: "Mixed descending progression with diminished predominant and V7 resolution.",
  },
  {
    id: "minor_i_iv_VII_III_VI_iio_V7_i",
    title: "i - iv - VII - III - VI - ii° - V7 - i",
    mode: "minor",
    difficulty: 5,
    roman: ["i", "iv", "VII", "III", "VI", "ii°", "V7", "i"],
    functions: ["T", "PD", "D", "T", "T", "PD", "D", "T"],
    tags: ["basic", "extended", "long", "fifths"],
    description: "Full circle of fifths progression in minor with chromatic diminished.",
  },
];
