import type { ProgressionTemplate } from "./types";

export const minorBasic: ProgressionTemplate[] = [
  {
    id: "min-basic-001",
    name: "i - V - i",
    mode: "minor",
    roman: ["i", "V", "i"],
    functions: ["T", "D", "T"],
    difficulty: 1,
    tags: ["basic", "cadence", "harmonic-minor"],
    description: "Authentic cadence in minor; V is borrowed from harmonic minor.",
    cadence: "authentic",
  },
  {
    id: "min-basic-002",
    name: "i - iv - V - i",
    mode: "minor",
    roman: ["i", "iv", "V", "i"],
    functions: ["T", "PD", "D", "T"],
    difficulty: 1,
    tags: ["basic", "cadence", "harmonic-minor"],
    description: "Standard minor T-PD-D-T cycle.",
    cadence: "authentic",
  },
  {
    id: "min-basic-003",
    name: "i - ii° - V - i",
    mode: "minor",
    roman: ["i", "ii°", "V", "i"],
    functions: ["T", "PD", "D", "T"],
    difficulty: 2,
    tags: ["basic", "harmonic-minor"],
    description: "Half-diminished ii° approach to V.",
    cadence: "authentic",
  },
  {
    id: "min-basic-004",
    name: "i - VI - VII - i",
    mode: "minor",
    roman: ["i", "VI", "VII", "i"],
    functions: ["T", "T", "D", "T"],
    difficulty: 1,
    tags: ["basic", "natural-minor", "modal"],
    description: "Natural minor without leading tone.",
    cadence: "authentic",
  },
  {
    id: "min-basic-005",
    name: "i - VII - VI - V",
    mode: "minor",
    roman: ["i", "VII", "VI", "V"],
    functions: ["T", "D", "T", "D"],
    difficulty: 2,
    tags: ["basic", "andalusian"],
    description: "Andalusian cadence (descending tetrachord).",
    cadence: "half",
  },
  {
    id: "min-basic-006",
    name: "i - iv - VII - III",
    mode: "minor",
    roman: ["i", "iv", "VII", "III"],
    functions: ["T", "PD", "D", "T"],
    difficulty: 2,
    tags: ["basic", "natural-minor"],
    description: "Pivots toward relative major via III.",
    cadence: "loop",
  },
  {
    id: "min-basic-007",
    name: "i - VI - III - VII",
    mode: "minor",
    roman: ["i", "VI", "III", "VII"],
    functions: ["T", "T", "T", "D"],
    difficulty: 2,
    tags: ["basic", "modal"],
    description: "Modal minor loop common in epic / cinematic music.",
    cadence: "loop",
  },
  {
    id: "min-basic-008",
    name: "i - iv - i - V",
    mode: "minor",
    roman: ["i", "iv", "i", "V"],
    functions: ["T", "PD", "T", "D"],
    difficulty: 1,
    tags: ["basic", "harmonic-minor"],
    description: "Alternation around tonic ending on dominant.",
    cadence: "half",
  },
  {
    id: "min-basic-009",
    name: "i - VII - III - VI",
    mode: "minor",
    roman: ["i", "VII", "III", "VI"],
    functions: ["T", "D", "T", "T"],
    difficulty: 2,
    tags: ["basic", "modal"],
    description: "Descending circle-of-fifths in natural minor.",
    cadence: "loop",
  },
  {
    id: "min-basic-010",
    name: "i - iv - V7 - i",
    mode: "minor",
    roman: ["i", "iv", "V7", "i"],
    functions: ["T", "PD", "D", "T"],
    difficulty: 2,
    tags: ["basic", "harmonic-minor", "seventh"],
    description: "Strong dominant 7th cadence in minor.",
    cadence: "authentic",
  },
  {
    id: "min-basic-011",
    name: "i - iv - ii° - V7 - i",
    mode: "minor",
    roman: ["i", "iv", "ii°", "V7", "i"],
    functions: ["T", "PD", "PD", "D", "T"],
    difficulty: 3,
    tags: ["basic", "harmonic-minor"],
    description: "Two predominants approach V7 in minor.",
    cadence: "authentic",
  },
  {
    id: "min-basic-012",
    name: "i - VI - iv - V7",
    mode: "minor",
    roman: ["i", "VI", "iv", "V7"],
    functions: ["T", "T", "PD", "D"],
    difficulty: 2,
    tags: ["basic", "harmonic-minor"],
    description: "Smooth predominant motion via VI.",
    cadence: "half",
  },
  {
    id: "min-basic-013",
    name: "i - bVII - bVI - V7",
    mode: "minor",
    roman: ["i", "bVII", "bVI", "V7"],
    functions: ["T", "D", "PD", "D"],
    difficulty: 3,
    tags: ["basic", "andalusian", "harmonic-minor"],
    description: "Classic Andalusian descent ending on dominant 7th.",
    cadence: "half",
  },
  {
    id: "min-basic-014",
    name: "i - VII - III - VI - ii° - V - i",
    mode: "minor",
    roman: ["i", "VII", "III", "VI", "ii°", "V", "i"],
    functions: ["T", "D", "T", "T", "PD", "D", "T"],
    difficulty: 3,
    tags: ["basic", "circle", "extended"],
    description: "Diatonic circle in minor with harmonic-minor cadence.",
    cadence: "authentic",
  },
  {
    id: "min-basic-015",
    name: "i - V - VI - iv",
    mode: "minor",
    roman: ["i", "V", "VI", "iv"],
    functions: ["T", "D", "T", "PD"],
    difficulty: 2,
    tags: ["basic", "deceptive"],
    description: "Deceptive resolution from V to VI.",
    cadence: "deceptive",
  },
  {
    id: "min-basic-016",
    name: "i - III - VII - VI",
    mode: "minor",
    roman: ["i", "III", "VII", "VI"],
    functions: ["T", "T", "D", "T"],
    difficulty: 2,
    tags: ["basic", "modal"],
    description: "Aeolian modal loop.",
    cadence: "loop",
  },
  {
    id: "min-basic-017",
    name: "i - iv - V - VI",
    mode: "minor",
    roman: ["i", "iv", "V", "VI"],
    functions: ["T", "PD", "D", "T"],
    difficulty: 2,
    tags: ["basic", "deceptive", "harmonic-minor"],
    description: "Deceptive cadence to VI instead of i.",
    cadence: "deceptive",
  },
  {
    id: "min-basic-018",
    name: "i - VI - VII - III - VI - ii° - V - i",
    mode: "minor",
    roman: ["i", "VI", "VII", "III", "VI", "ii°", "V", "i"],
    functions: ["T", "T", "D", "T", "T", "PD", "D", "T"],
    difficulty: 4,
    tags: ["basic", "extended", "harmonic-minor"],
    description: "Long phrase passing through relative major then back.",
    cadence: "authentic",
  },
];
