import { ProgressionTemplate } from "./types";

export const pop: ProgressionTemplate[] = [
  {
    id: "pop_I_V_vi_IV",
    title: "I - V - vi - IV (Axis)",
    mode: "major",
    difficulty: 2,
    roman: ["I", "V", "vi", "IV"],
    functions: ["T", "D", "T", "PD"],
    tags: ["pop", "axis", "ubiquitous"],
    description: "The Axis progression — used in hundreds of pop songs. Let It Be, Don't Stop Believin'.",
  },
  {
    id: "pop_vi_IV_I_V",
    title: "vi - IV - I - V (Axis reversed)",
    mode: "major",
    difficulty: 3,
    roman: ["vi", "IV", "I", "V"],
    functions: ["T", "PD", "T", "D"],
    tags: ["pop", "axis-variant"],
    description: "Axis progression starting on the relative minor. Zombie, Numb.",
  },
  {
    id: "pop_I_vi_IV_V",
    title: "I - vi - IV - V (Doo-wop)",
    mode: "major",
    difficulty: 2,
    roman: ["I", "vi", "IV", "V"],
    functions: ["T", "T", "PD", "D"],
    tags: ["pop", "doo-wop", "50s"],
    description: "The classic 1950s doo-wop and early rock progression.",
  },
  {
    id: "pop_I_V_vi_iii_IV_I_IV_V",
    title: "Canon (Pachelbel)",
    mode: "major",
    difficulty: 5,
    roman: ["I", "V", "vi", "iii", "IV", "I", "IV", "V"],
    functions: ["T", "D", "T", "T", "PD", "T", "PD", "D"],
    tags: ["pop", "canon", "long"],
    description: "Pachelbel's Canon progression, basis for many pop songs.",
  },
  {
    id: "pop_I_V_IV_V",
    title: "I - V - IV - V",
    mode: "major",
    difficulty: 1,
    roman: ["I", "V", "IV", "V"],
    functions: ["T", "D", "PD", "D"],
    tags: ["pop", "loop", "simple"],
    description: "Simple loop alternating dominant and subdominant.",
  },
  {
    id: "pop_I_IV_V_IV",
    title: "I - IV - V - IV",
    mode: "major",
    difficulty: 1,
    roman: ["I", "IV", "V", "IV"],
    functions: ["T", "PD", "D", "PD"],
    tags: ["pop", "loop"],
    description: "Another common pop loop, Louie Louie style.",
  },
  {
    id: "pop_I_bVII_IV_I",
    title: "I - bVII - IV - I (Mixolydian)",
    mode: "major",
    difficulty: 4,
    roman: ["I", "VII", "IV", "I"],
    functions: ["T", "D", "PD", "T"],
    tags: ["pop", "modal", "rock"],
    description: "Rock Mixolydian progression with flat VII. Sweet Home Alabama.",
  },
  {
    id: "pop_I_V_vi_V",
    title: "I - V - vi - V",
    mode: "major",
    difficulty: 2,
    roman: ["I", "V", "vi", "V"],
    functions: ["T", "D", "T", "D"],
    tags: ["pop", "loop"],
    description: "Alternating between relative minor and dominant.",
  },
  {
    id: "pop_I_iii_vi_IV",
    title: "I - iii - vi - IV",
    mode: "major",
    difficulty: 3,
    roman: ["I", "iii", "vi", "IV"],
    functions: ["T", "T", "T", "PD"],
    tags: ["pop", "descending"],
    description: "Descending thirds loop, popular in indie pop.",
  },
  {
    id: "pop_I_vi_ii_V",
    title: "I - vi - ii - V",
    mode: "major",
    difficulty: 3,
    roman: ["I", "vi", "ii", "V"],
    functions: ["T", "T", "PD", "D"],
    tags: ["pop", "jazz-influenced"],
    description: "Circle of fifths fragments, common in jazz-influenced pop.",
  },
  {
    id: "pop_IV_I_V_vi",
    title: "IV - I - V - vi",
    mode: "major",
    difficulty: 3,
    roman: ["IV", "I", "V", "vi"],
    functions: ["PD", "T", "D", "T"],
    tags: ["pop", "anacrusis"],
    description: "Starting on IV for a floating, anacrusis feel.",
  },
  {
    id: "pop_vi_V_IV_III",
    title: "vi - V - IV - III",
    mode: "major",
    difficulty: 4,
    roman: ["vi", "V", "IV", "III"],
    functions: ["T", "D", "PD", "T"],
    tags: ["pop", "descending", "epic"],
    description: "Descending bass line creates an epic feel.",
  },
  {
    id: "pop_I_IV_vi_V",
    title: "I - IV - vi - V",
    mode: "major",
    difficulty: 2,
    roman: ["I", "IV", "vi", "V"],
    functions: ["T", "PD", "T", "D"],
    tags: ["pop", "variant"],
    description: "Like doo-wop but tonic substitute before dominant.",
  },
  {
    id: "pop_I_V7_vi_IV",
    title: "I - V7 - vi - IV",
    mode: "major",
    difficulty: 3,
    roman: ["I", "V7", "vi", "IV"],
    functions: ["T", "D", "T", "PD"],
    tags: ["pop", "axis", "seventh"],
    description: "Axis variant with dominant seventh for color.",
  },
  {
    id: "pop_I_IV_I_V",
    title: "I - IV - I - V (Blues)",
    mode: "major",
    difficulty: 1,
    roman: ["I", "IV", "I", "V"],
    functions: ["T", "PD", "T", "D"],
    tags: ["pop", "blues", "rock"],
    description: "Blues turnaround, fundamental to rock and pop.",
  },
  {
    id: "pop_i_bVII_bVI_bVII",
    title: "i - bVII - bVI - bVII (Rock minor)",
    mode: "minor",
    difficulty: 2,
    roman: ["i", "VII", "VI", "VII"],
    functions: ["T", "D", "T", "D"],
    tags: ["pop", "rock", "minor"],
    description: "Classic rock minor loop. All Along the Watchtower.",
  },
  {
    id: "pop_i_bVI_bVII_i",
    title: "i - bVI - bVII - i",
    mode: "minor",
    difficulty: 2,
    roman: ["i", "VI", "VII", "i"],
    functions: ["T", "T", "D", "T"],
    tags: ["pop", "rock", "aeolian"],
    description: "Aeolian progression with major VI and flat VII.",
  },
  {
    id: "pop_IV_V_iii_vi",
    title: "IV - V - iii - vi (Royal Road)",
    mode: "major",
    difficulty: 3,
    roman: ["IV", "V", "iii", "vi"],
    functions: ["PD", "D", "T", "T"],
    tags: ["pop", "japanese", "royal-road", "王道進行"],
    description: "王道進行 — iconic Japanese pop progression found in anime and J-pop hits.",
  },
  {
    id: "pop_vi_V_IV_I",
    title: "vi - V - IV - I",
    mode: "major",
    difficulty: 2,
    roman: ["vi", "V", "IV", "I"],
    functions: ["T", "D", "PD", "T"],
    tags: ["pop", "descending", "loop"],
    description: "Descending bass from relative minor to tonic.",
  },
  {
    id: "pop_I_V_ii_IV_I",
    title: "I - V - ii - IV - I",
    mode: "major",
    difficulty: 2,
    roman: ["I", "V", "ii", "IV", "I"],
    functions: ["T", "D", "PD", "PD", "T"],
    tags: ["pop", "loop"],
    description: "Simple pop loop with subdominant chain.",
  },
  {
    id: "pop_I_VII_IV_V",
    title: "I - VII - IV - V (Mixolydian)",
    mode: "major",
    difficulty: 3,
    roman: ["I", "VII", "IV", "V"],
    functions: ["T", "D", "PD", "D"],
    tags: ["pop", "modal", "rock", "mixolydian"],
    description: "Mixolydian rock progression with flat VII. Classic guitar-driven sound.",
  },
  {
    id: "pop_I_V7_IV_iii_vi",
    title: "I - V7 - IV - iii - vi",
    mode: "major",
    difficulty: 3,
    roman: ["I", "V7", "IV", "iii", "vi"],
    functions: ["T", "D", "PD", "T", "T"],
    tags: ["pop", "axis-variant"],
    description: "Axis variant extending through predominant to descending tonic area.",
  },
  {
    id: "pop_I_vi_V7_IV_I",
    title: "I - vi - V7 - IV - I",
    mode: "major",
    difficulty: 3,
    roman: ["I", "vi", "V7", "IV", "I"],
    functions: ["T", "T", "D", "PD", "T"],
    tags: ["pop", "classic"],
    description: "Classic pop cadence with dominant seventh in the middle.",
  },
  {
    id: "pop_i_VI_VII_iv_V7",
    title: "i - VI - VII - iv - V7",
    mode: "minor",
    difficulty: 3,
    roman: ["i", "VI", "VII", "iv", "V7"],
    functions: ["T", "T", "D", "PD", "D"],
    tags: ["pop", "minor", "rock"],
    description: "Minor pop progression with subdominant to dominant tension.",
  },
  {
    id: "pop_I_I7_IV_iv_I_V",
    title: "I - I7 - IV - iv - I - V (Creep)",
    mode: "major",
    difficulty: 4,
    roman: ["I", "I7", "IV", "iv", "I", "V"],
    functions: ["T", "T", "PD", "PD", "T", "D"],
    tags: ["pop", "chromatic", "creep"],
    description: "Chromatic descending line from I7 to borrowed minor iv. Famously used in Creep.",
  },
  {
    id: "pop_vi_IV_I_iii_ii_V_I",
    title: "vi - IV - I - iii - ii - V - I",
    mode: "major",
    difficulty: 4,
    roman: ["vi", "IV", "I", "iii", "ii", "V", "I"],
    functions: ["T", "PD", "T", "T", "PD", "D", "T"],
    tags: ["pop", "extended"],
    description: "Extended pop progression with tonic expansion and cadential resolution.",
  },
  {
    id: "pop_I_IV_vi_iii_ii_V",
    title: "I - IV - vi - iii - ii - V",
    mode: "major",
    difficulty: 4,
    roman: ["I", "IV", "vi", "iii", "ii", "V"],
    functions: ["T", "PD", "T", "T", "PD", "D"],
    tags: ["pop", "descending", "extended"],
    description: "Extended predominant chain with descending tonic area.",
  },
  {
    id: "pop_I_IV_I_VII_IV",
    title: "I - IV - I - VII - IV (Mixolydian loop)",
    mode: "major",
    difficulty: 4,
    roman: ["I", "IV", "I", "VII", "IV"],
    functions: ["T", "PD", "T", "D", "PD"],
    tags: ["pop", "modal", "mixolydian", "loop"],
    description: "Extended Mixolydian loop alternating tonic, subdominant, and flat VII.",
  },
  {
    id: "pop_IV_V_iii_vi_ii_V_I",
    title: "IV - V - iii - vi - ii - V - I (Extended Royal Road)",
    mode: "major",
    difficulty: 5,
    roman: ["IV", "V", "iii", "vi", "ii", "V", "I"],
    functions: ["PD", "D", "T", "T", "PD", "D", "T"],
    tags: ["pop", "japanese", "royal-road", "long", "王道進行"],
    description: "Extended Royal Road — full 王道進行 with ii-V-I resolution.",
  },
  {
    id: "pop_I_V_vi_iii_IV_I_ii_V",
    title: "I - V - vi - iii - IV - I - ii - V (Canon 15634125)",
    mode: "major",
    difficulty: 5,
    roman: ["I", "V", "vi", "iii", "IV", "I", "ii", "V"],
    functions: ["T", "D", "T", "T", "PD", "T", "PD", "D"],
    tags: ["pop", "canon", "long", "pachelbel"],
    description: "Pachelbel Canon with ii-V ending for smoother loop. Countless pop songs use this.",
  },
];
