import type { ProgressionTemplate } from "./types";

export const pop: ProgressionTemplate[] = [
  {
    id: "pop-001",
    name: "I - V - vi - IV (Axis)",
    mode: "major",
    roman: ["I", "V", "vi", "IV"],
    functions: ["T", "D", "T", "PD"],
    difficulty: 1,
    tags: ["pop", "axis", "loop"],
    description: "The Axis of Awesome progression — countless modern hits.",
    cadence: "loop",
  },
  {
    id: "pop-002",
    name: "vi - IV - I - V",
    mode: "major",
    roman: ["vi", "IV", "I", "V"],
    functions: ["T", "PD", "T", "D"],
    difficulty: 1,
    tags: ["pop", "loop"],
    description: "Axis rotated to start on vi.",
    cadence: "loop",
  },
  {
    id: "pop-003",
    name: "I - vi - IV - V (50s)",
    mode: "major",
    roman: ["I", "vi", "IV", "V"],
    functions: ["T", "T", "PD", "D"],
    difficulty: 1,
    tags: ["pop", "doo-wop", "loop"],
    description: "1950s doo-wop loop.",
    cadence: "loop",
  },
  {
    id: "pop-004",
    name: "I - V - vi - iii - IV - I - IV - V (Pachelbel)",
    mode: "major",
    roman: ["I", "V", "vi", "iii", "IV", "I", "IV", "V"],
    functions: ["T", "D", "T", "T", "PD", "T", "PD", "D"],
    difficulty: 3,
    tags: ["pop", "canon"],
    description: "Pachelbel descending bass — used in countless pop songs.",
    cadence: "half",
  },
  {
    id: "pop-005",
    name: "I - V - IV - V",
    mode: "major",
    roman: ["I", "V", "IV", "V"],
    functions: ["T", "D", "PD", "D"],
    difficulty: 1,
    tags: ["pop", "loop"],
    description: "Bouncy half-cadence loop common in 60s pop.",
    cadence: "loop",
  },
  {
    id: "pop-006",
    name: "I - IV - V - IV",
    mode: "major",
    roman: ["I", "IV", "V", "IV"],
    functions: ["T", "PD", "D", "PD"],
    difficulty: 1,
    tags: ["pop", "rock", "loop"],
    description: "Three-chord rock loop.",
    cadence: "loop",
  },
  {
    id: "pop-007",
    name: "I - bVII - IV - I (Mixolydian)",
    mode: "major",
    roman: ["I", "bVII", "IV", "I"],
    functions: ["T", "OTHER", "PD", "T"],
    difficulty: 2,
    tags: ["pop", "rock", "mixolydian"],
    description: "Mixolydian colour with a flat seventh chord.",
    cadence: "plagal",
  },
  {
    id: "pop-008",
    name: "I - V - vi - V",
    mode: "major",
    roman: ["I", "V", "vi", "V"],
    functions: ["T", "D", "T", "D"],
    difficulty: 1,
    tags: ["pop", "loop"],
    description: "V-vi-V dance between dominants.",
    cadence: "loop",
  },
  {
    id: "pop-009",
    name: "I - iii - vi - IV",
    mode: "major",
    roman: ["I", "iii", "vi", "IV"],
    functions: ["T", "T", "T", "PD"],
    difficulty: 2,
    tags: ["pop"],
    description: "Tonic-prolongation pop loop.",
    cadence: "loop",
  },
  {
    id: "pop-010",
    name: "I - vi - ii - V (Heart and Soul)",
    mode: "major",
    roman: ["I", "vi", "ii", "V"],
    functions: ["T", "T", "PD", "D"],
    difficulty: 1,
    tags: ["pop", "doo-wop", "loop"],
    description: "Doo-wop / Heart-and-Soul progression.",
    cadence: "loop",
  },
  {
    id: "pop-011",
    name: "vi - V - IV - V",
    mode: "major",
    roman: ["vi", "V", "IV", "V"],
    functions: ["T", "D", "PD", "D"],
    difficulty: 2,
    tags: ["pop", "loop"],
    description: "Alt-rock minor-feel loop in major key.",
    cadence: "half",
  },
  {
    id: "pop-012",
    name: "I - IV - vi - V (Pop Punk)",
    mode: "major",
    roman: ["I", "IV", "vi", "V"],
    functions: ["T", "PD", "T", "D"],
    difficulty: 1,
    tags: ["pop", "punk", "loop"],
    description: "Pop-punk standard.",
    cadence: "half",
  },
  {
    id: "pop-013",
    name: "I - V - vi - IV - I - V - IV",
    mode: "major",
    roman: ["I", "V", "vi", "IV", "I", "V", "IV"],
    functions: ["T", "D", "T", "PD", "T", "D", "PD"],
    difficulty: 2,
    tags: ["pop", "extended"],
    description: "Extended Axis with a dropped final chord.",
    cadence: "plagal",
  },
  {
    id: "pop-014",
    name: "I - V - IV - I (Power-Pop)",
    mode: "major",
    roman: ["I", "V", "IV", "I"],
    functions: ["T", "D", "PD", "T"],
    difficulty: 1,
    tags: ["pop", "rock"],
    description: "Tonic with brief D→PD detour.",
    cadence: "plagal",
  },
  {
    id: "pop-015",
    name: "vi - IV - V - I",
    mode: "major",
    roman: ["vi", "IV", "V", "I"],
    functions: ["T", "PD", "D", "T"],
    difficulty: 1,
    tags: ["pop"],
    description: "Anti-Axis: ends on tonic instead of looping back.",
    cadence: "authentic",
  },
  {
    id: "pop-016",
    name: "I - V - vi - iii - IV",
    mode: "major",
    roman: ["I", "V", "vi", "iii", "IV"],
    functions: ["T", "D", "T", "T", "PD"],
    difficulty: 2,
    tags: ["pop", "canon"],
    description: "First half of the Pachelbel pattern.",
    cadence: "none",
  },
  {
    id: "pop-017",
    name: "i - VI - III - VII (Modal Pop)",
    mode: "minor",
    roman: ["i", "VI", "III", "VII"],
    functions: ["T", "T", "T", "D"],
    difficulty: 2,
    tags: ["pop", "modal", "minor-pop"],
    description: "Aeolian pop loop in minor.",
    cadence: "loop",
  },
];
